apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/BadaBoum13/homelab-public.git
    targetRevision: HEAD
    path: app/security/cert-manager
    directory:
      recurse: false
      include: "cloudflare-issuer.yml"
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
