---
version: '3'

tasks:
  default:
    desc: Deploy cert-manager
    cmds:
      - task: deploy

  deploy:
    desc: Deploy cert-manager using Helm
    vars:
      NAMESPACE: security
      REPO_NAME: oci://quay.io/jetstack/charts/cert-manager
      RELEASE_NAME: cert-manager
    cmds:
      - helm upgrade --install {{.RELEASE_NAME}} {{.REPO_NAME}} -n {{.NAMESPACE}} -f {{.TASKFILE_DIR}}/values.yml
      - kubectl apply -f {{.TASKFILE_DIR}}/crd

  clean:
    desc: Remove cert-manager
    vars:
      NAMESPACE: security
      RELEASE_NAME: cert-manager
    cmds:
      - helm uninstall {{.RELEASE_NAME}} -n {{.NAMESPACE}} --ignore-not-found
