global:
  logLevel: 2 # Set the log level, 2 is info and 6 is the most verbose.

crds:
  enabled: true
  keep: true

resources:
  limits:
    cpu: 256m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

prometheus:
  enabled: true
  servicemonitor:
    enabled: true
