apiVersion: operator.victoriametrics.com/v1
kind: VLSingle
metadata:
  name: vl-single
  namespace: monitoring
spec:
  # TODO pin the version to upgrade the vm compoment when necessary
  # image:
  #   repository:
  #   tag: 
  #   pullPolicy: Always
  replicaCount: 1
  retentionPeriod: "10d"
  storage:
    storageClassName: longhorn-ssd
    resources:
      requests:
        storage: 15Gi
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "1000m"
