apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: monitoring
spec:
  serviceScrapeNamespaceSelector: {}
  serviceScrapeSelector: {}
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  nodeScrapeNamespaceSelector: {}
  nodeScrapeSelector: {}
  
  remoteWrite:
    - url: http://vmsingle-vm-single.monitoring.svc.cluster.local:8429/api/v1/write

  scrapeInterval: 30s
  scrapeTimeout: 10s
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
