apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: oci://ghcr.io/prometheus-community/charts
      chart: kube-state-metrics
      targetRevision: "6.1.4"
      helm:
        valueFiles:
          - $values/app/monitoring/kube-state-metrics/values.yaml
    - repoURL: https://github.com/BadaBoum13/homelab-public.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
