---
version: '3'

tasks:
  default:
    desc: Deploy kube-state-metrics
    cmds:
      - task: deploy

  deploy:
    desc: Deploy kube-state-metrics using Helm
    vars:
      NAMESPACE: monitoring
      REPO_NAME: oci://ghcr.io/prometheus-community/charts/kube-state-metrics
      RELEASE_NAME: kube-state-metrics
    cmds:
      - helm upgrade --install {{.RELEASE_NAME}} {{.REPO_NAME}} -n {{.NAMESPACE}} -f {{.TASKFILE_DIR}}/values.yaml

  clean:
    desc: Remove kube-state-metrics
    vars:
      NAMESPACE: monitoring
      RELEASE_NAME: kube-state-metrics
    cmds:
      - helm uninstall {{.RELEASE_NAME}} -n {{.NAMESPACE}} --ignore-not-found
