---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victorialogs-datasource
  namespace: monitoring
spec:
  datasource:
    name: victorialogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://vlsingle-vl-single.monitoring.svc.cluster.local:9428
    isDefault: false
    editable: true
  instanceSelector:
    matchLabels:
      app: "grafana"
  plugins:
    - name: victoriametrics-metrics-datasource
      version: latest
    - name: victoriametrics-logs-datasource
      version: latest