apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-secret
  namespace: shared
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: postgresql-secret
    creationPolicy: Owner
  data:
    - secretKey: postgres-admin-password
      remoteRef:
        key: postgresql-admin
        property: password
    - secretKey: postgres-user-password
      remoteRef:
        key: postgresql-user
        property: password
