apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - fluxcd.yaml

configMapGenerator:
  - name: vector-values
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true
