---
version: '3'

tasks:
  default:
    desc: Deploy Vector
    cmds:
      - task: deploy

  repos:
    desc: Add Vector Helm repository
    vars:
      REPO_NAME: vector
    cmds:
      - helm repo add {{.REPO_NAME}} https://helm.vector.dev/
      - helm repo update {{.REPO_NAME}}

  deploy:
    desc: Deploy Vector using Helm
    vars:
      MONITORING_NS: monitoring
      CHART_NAME: vector
      REPO_NAME: vector
      RELEASE_NAME: vector
    cmds:
      - helm upgrade --install {{.RELEASE_NAME}} {{.REPO_NAME}}/{{.CHART_NAME}} -n {{.MONITORING_NS}} -f {{.TASKFILE_DIR}}/values.yaml

  clean:
    desc: Remove Vector
    vars:
      MONITORING_NS: monitoring
      RELEASE_NAME: vector
    cmds:
      - helm uninstall {{.RELEASE_NAME}} -n {{.MONITORING_NS}} --ignore-not-found
