apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-config-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://redhat-cop.github.io/vault-config-operator
      chart: vault-config-operator
      targetRevision: v0.8.52
      helm:
        valueFiles:
          - $values/app/security/vault-config-operator/values.yml
    - repoURL: https://github.com/BadaBoum13/homelab-public.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
