apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: default-db-password
spec:
  kind: VaultDynamicSecret
  generator:
    vaultDynamicSecretSpec:
      path: "/sys/tools/random/32"
      method: "POST"
      parameters:
        format: "hex"
      resultType: "Data"
      provider:
        server: "http://openbao.security.svc.cluster.local:8200"
        auth:
          kubernetes:
            mountPath: "kubernetes"
            role: "external-secrets"
            serviceAccountRef:
              name: "external-secrets"
              namespace: "security"
