---
version: '3'

tasks:
  default:
    desc: Deploy Longhorn
    cmds:
      - task: deploy

  repos:
    desc: Add Longhorn Helm repository
    vars:
      REPO_NAME: longhorn
    cmds:
      - helm repo add {{.REPO_NAME}} https://charts.longhorn.io
      - helm repo update {{.REPO_NAME}}

  deploy:
    desc: Deploy Longhorn using Helm
    vars:
      NAMESPACE: longhorn-system
      CHART_NAME: longhorn
      REPO_NAME: longhorn
      RELEASE_NAME: longhorn
    cmds:
      - helm upgrade --install {{.RELEASE_NAME}} {{.REPO_NAME}}/{{.CHART_NAME}} -n {{.NAMESPACE}} -f {{.TASKFILE_DIR}}/values.yml
      - kubectl apply -f {{.TASKFILE_DIR}}/crd

  clean:
    desc: Remove Longhorn
    vars:
      NAMESPACE: longhorn-system
      RELEASE_NAME: longhorn
    cmds:
      - kubectl delete -f {{.TASKFILE_DIR}}/crd --ignore-not-found
      - helm uninstall {{.RELEASE_NAME}} -n {{.NAMESPACE}} --ignore-not-found
