defaultSettings:
  defaultDataPath: "/mnt/long_storage"   # Path where SSD
  defaultReplicaCount: 1
  #nodeDownPodDeletionPolicy: "do-nothing"

ingress:
  enabled: true
  host: longhorn.biduleproofzone.ovh
  ingressClassName: traefik
  tls: true
  secureBackends: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "cloudflare"


persistence:
  defaultClass: true
  defaultClassReplicaCount: 1

longhornDriver:
  log:
    format: json
  nodeSelector:
    storage-raid: "true"

longhornUI:
  replicas: 1

csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1
