defaultSettings:
  defaultDataPath: "/mnt/long_storage"   # Path where SSD
  defaultReplicaCount: 1
  #nodeDownPodDeletionPolicy: "do-nothing"

ingress:
  enabled: true
  host: homelab.inconnu-teeth.ts.net
  ingressClassName: traefik
  annotations:
    kubernetes.io/ingress.class: "traefik"


persistence:
  defaultClass: true
  defaultClassReplicaCount: 1

longhornDriver:
  log:
    # -- Format of longhorn-driver logs. (Options: "plain", "json")
    format: plain
  nodeSelector:
    storage-raid: "true"

longhornUI:
  replicas: 1

csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1
