apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
data:
  config.json: |
    {
      "$schema": "https://docs.renovatebot.com/renovate-schema.json",
      "platform": "github",
      "repositories": ["BadaBoum13/homelab-public"],
      "autodiscover": false,
      "onboarding": false,
      "requireConfig": "optional",
      "extends": ["config:recommended"],
      "prConcurrentLimit": 5,
      "enabledManagers": ["argocd", "ansible-galaxy"],
      "argocd": {
        "managerFilePatterns": ["/^app\\/.*argocd-helm.*\\.yaml$/"]
      },
      "packageRules": [
        { "matchFileNames": ["app/deprecated/**"], "enabled": false },
        {
          "matchUpdateTypes": ["minor", "patch"],
          "automerge": true,
          "automergeType": "pr",
          "platformAutomerge": true
        },
        {
          "reviewers": ["BadaBoum13"]
        }
      ]
    }
