global:
  domain: argocd.biduleproofzone.ovh
  logging:
    # -- Set the global logging format. Either: `text` or `json`
    format: json
    # -- Set the global logging level. One of: `debug`, `info`, `warn` or `error`
    level: warn

crds:
  install: false

# TODO: can fix the ingress
# config:
#   params:
#     create: true
#     server:
#       insecure: "true"

server:
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      kubernetes.io/ingress.class: "traefik"
      cert-manager.io/cluster-issuer: "cloudflare"
    tls: true
  certificate:
    enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

controller:
  replicas: 1
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    rules:
      enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

configs:
  cm:
    url: https://argocd.biduleproofzone.ovh
    oidc.config: |
      name: Auth0
      issuer: $oidc.auth0.issuer
      clientID: $oidc.auth0.clientID
      clientSecret: $oidc.auth0.clientSecret
      requestedScopes:
        - openid
        - profile
        - email

dex:
  enabled: false

redis:
  enabled: true
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  exporter:
    enabled: false
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

repoServer:
  replicas: 1
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

applicationSet:
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

notifications:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true

commitServer:
  enabled: false