k3s_control_node: true
k3s_server:
  write-kubeconfig-mode: '0644'

storage:
  enable: true
  device_id: "cdc77249-f74c-4eb4-a423-69831486ed8d"
  fs_type: "ext4"
  path_mount: "/mnt/long_storage"


k3s_agent:
  node-label:
    - "storage-raid=true"

tailscale:
  # auth_key: "--auth-key="
  opt: "--advertise-exit-node --ssh --hostname=homelab"
