---
version: '3'

tasks:
  default:
    desc: Deploy Prometheus Operator CRDs
    cmds:
      - task: deploy

  deploy:
    desc: Deploy Prometheus Operator CRDs using Helm
    vars:
      NAMESPACE: monitoring
      REPO_NAME: oci://ghcr.io/prometheus-community/charts/prometheus-operator-crds
      RELEASE_NAME: prometheus-operator-crds
    cmds:
      - helm upgrade --install {{.RELEASE_NAME}} {{.REPO_NAME}} -n {{.NAMESPACE}} --create-namespace

  clean:
    desc: Remove Prometheus Operator CRDs
    vars:
      NAMESPACE: monitoring
      RELEASE_NAME: prometheus-operator-crds
    cmds:
      - helm uninstall {{.RELEASE_NAME}} -n {{.NAMESPACE}} --ignore-not-found
