
k3s_cluster:
  children:
    controlplane1
    # pi:

amd64:
  children:
    controlplane1

arm:
  children:
    pi

tailscale:
  children:
    controlplane1

controlplane1:
  hosts:
    node0:
      ansible_user: root
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      ansible_python_interpreter: /usr/bin/python3
      ansible_password: password123