apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/BadaBoum13/homelab-public.git
    targetRevision: HEAD
    path: app/monitoring/grafana
    directory:
      recurse: false
      include: "external-secret.yml"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
