apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  targetNamespace: monitoring
  releaseName: grafana
  valuesFrom:
    - kind: ConfigMap
      name: grafana-values
  chart:
    spec:
      chart: grafana
      # version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
