# Grafana Operator Helm Chart Values
# Reference: https://github.com/grafana/helm-charts/blob/main/charts/grafana-operator/values.yaml
replicas: 1
namespaceScope: true

dashboard:
  # -- Whether to create a ConfigMap containing a dashboard monitoring the operator metrics.
  # Consider enabling this if you are enabling the ServiceMonitor.
  # Optionally, a GrafanaDashboard CR can be manually created pointing to the Grafana.com dashboard ID 22785
  # https://grafana.com/grafana/dashboards/22785-grafana-operator/
  # The Grafana.com dashboard is maintained by the community and does not necessarily match the JSON definition in this repository.
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceMonitor:
  enabled: true
